Disease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('appointment/', include('appointment.urls')),
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('doctor/',include('doctor.urls')),
    path('roleadmin/',include('roleadmin.urls')),
    path('patient/',include('patient.urls')),
    path('health/',include('Health.urls')),
    path('', RedirectView.as_view(url="health/")),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = 'Smart Health'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"

patient/urls.py
from django.urls import path
from patient import views
from django.views.generic.base import RedirectView

1
urlpatterns = [
path('chat/',views.chat,name="chat"),
path('patient/',RedirectView.as_view(url='patient_login/')),
path('patient_login/', views.patient_login,name='patient_login'),
path('patient_register/', views.patient_register,name='patient_register'),
path('patient_profile/',views.patient_profile,name='patient_profile'),
path('my_profile/',views.my_profile,name="my_profile"),
path('search_doctor/', views.search_doctor,name="search_doctor"),
path('search_doctor/doctor_profile/<int:pk>',views.doctor_profile),
path('dashboard/', views.dashboard, name="dashboard"),
path('home/',views.home,name="home"),
path('home/doctor_profile/<int:pk>',views.doctor_profile),
path('feedback/',views.feedback,name="feedback"),
path('feedback/detail/<int:pk>',views.feedback_detail),
path('feedback/edit/<int:pk>',views.feedback_edit),
path('feedback/add_feedback',views.feedback_add),
path('feedback/delete/<int:pk>',views.feedback_delete),
path('view_appointment/',views.view_appointment,name="view_appointment"),
path('patient_appointment/',views.patient_appointment,name="patient_appointment"),
path('view_appointment/take/<int:pk>',views.take_appointment),
path('patient_appointment/cancel/<int:pk>',views.cancel_appointment),
path('patient_appointment/details/<int:pk>',views.details_appointment),
path('patient_appointment/details/<int:pk>/export_pdf',views.export_pdf),
path('logoutpatient/', views.logoutpatient, name="logoutpatient"),
path('heart/', views.heart, name="heart"),
path('diabetes/', views.diabetes, name="diabetes"),
path('showimage/', views.showimage, name="showimage"),
]

urls.py
from django.contrib import admin
from django.urls import path,include
from doctor import views
from django.views.generic.base import RedirectView

urlpatterns = [        
path('doctor/',RedirectView.as_view(url='doctor_login/')),
path('doctor_login/', views.doctor_login,name='doctor_login'),
path('prescription/', views.prescription,name='prescription'),

path('dashboard_doctor/', views.dashboard_doctor, name="dashboard_doctor"),
path('doctor_logout/', views.doctor_logout, name="doctor_logout"),
path('appointment/', views.appointment, name="appointment"),
path('book_appointment/',views.book_appointment,name="book_appointment"),
path('appointment/add_appointment/',views.add_appointment),
path('appointment/edit/<int:pk>',views.edit_appointment),
path('appointment/delete/<int:pk>',views.delete_appointment),
path('book_appointment/delete/<int:pk>',views.delete_booked_appointment),


]

doctor/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


# Create your models here.
class DoctorInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    address=models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    picture=models.ImageField(blank=True,null=True)
    department=models.CharField(max_length=30)
    gender=models.CharField( max_length=50,blank=True,choices=(('Female','Female'),('Male','Male'),('Other','Other')))
    doctorID=models.CharField(max_length=50,unique=True)
    education_college=models.CharField(max_length=100)
    education_degree=models.CharField(max_length=100)
    education_year=models.DateTimeField()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_instance(self):
        return self

patient/models.py
from django.db import models
from django.core.validators import  RegexValidator
from django.db.models import CASCADE
from django.contrib.auth.models import User
#from patient.models import PatientInfo
from django.db.models.signals import post_save
from django.db.models import signals
from django.dispatch import receiver
from doctor.models import *

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    address=models.CharField(max_length=40)
    gender=models.CharField( max_length=50,blank=True,choices=(('Female','Female'),('Male','Male'),('Other','Other')))
    age=models.IntegerField(blank=True , null=True)
    status=models.CharField(max_length=20,blank=True,choices=(('Single','Single'),('Married','Married')))
    profile_pic=models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
	if created:
		Profile.objects.create(user=instance,name=instance.username)


@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
	instance.profile.save()

# when profile is deleted user is also delete
def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()
signals.post_delete.connect(delete_user, sender=Profile)

class Feedback(models.Model):
    text=models.TextField(max_length=200)
    title=models.CharField(max_length=50)
    date=models.DateTimeField(auto_now_add=True)
    uploaded_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class WhoPredictDisease(models.Model):
    predict_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    predicted_disease=models.CharField(max_length=30)

    def __str__(self):
        return self.predicted_disease


class Disease1(models.Model):
    name=models.CharField(max_length=200)
    doctor=models.ForeignKey(DoctorInfo,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name

# Create your models here.
class Heart(models.Model):
    age=models.IntegerField()
    sex=models.IntegerField()
    cp=models.IntegerField()
    trestbps=models.IntegerField()
    chol=models.IntegerField()
    fbs=models.IntegerField()
    restecg=models.IntegerField()
    thalach=models.IntegerField()
    exang=models.IntegerField()
    oldpeak=models.IntegerField()
    slope=models.IntegerField()
    ca	=models.IntegerField()
    thal=models.IntegerField()
    def to_dict(self):
        return{
            'age':self.age,
            'sex':self.sex,
            'cp':self.cp,
            'trestbps':self.trestbps,
            'chol':self.chol,
            'fbs':self.fbs,
            'restecg':self.restecg,
            'thalach':self.thalach,
            'exang':self.exang,
            'slope':self.slope,
            'oldpeak':self.oldpeak,
            'ca':self.ca,
            'thal':self.thal,

        }

class Diabetes(models.Model):
    Pregnancies=models.IntegerField()
    Glucose=models.IntegerField()
    BloodPressure=models.IntegerField()
    SkinThickness=models.IntegerField()
    Insulin=models.IntegerField()
    BMI=models.IntegerField()
    DiabetesPedigreeFunction=models.IntegerField()
    Age=models.IntegerField()

    def to_dict(self):
        return{
            'Pregnancies':self.Pregnancies,
            'Glucose':self.Glucose,
            'BloodPressure':self.BloodPressure,
            'SkinThickness':self.SkinThickness,
            'Insulin':self.Insulin,
            'BMI':self.BMI,
            'DiabetesPedigreeFunction':self.DiabetesPedigreeFunction,
            'Age':self.Age,
        }

class Image(models.Model):

    imagefile= models.FileField(upload_to='images/')

class ImageBlock(models.Model):
    imageblock = models.FileField(upload_to='images/')

patient/forms.py
from django import forms
from django.contrib.auth.models import User
from patient.models import Profile,Feedback
from django.contrib.auth.forms import UserCreationForm

class PatientInfoForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        # fields='__all__'
        fields = ('username','password')

class UserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']



class ProfileForm(forms.ModelForm):

	class Meta:
		model=Profile
		fields=('name','phone_number','address','gender','age','status','profile_pic')
		#exclude=['username','password']
		label={

			'phone_number':'Phone Number',
			'address':'Address',
			'gender':'Gender',
			'age':'Age',
			'status':'Status',
			'profile_pic':'Profile Picture'

		}
	def __init__(self,*args,**kwargs):
		super(ProfileForm,self).__init__(*args,**kwargs)

		self.fields['name'].error_messages.update({'required':'Name can hold atmost 20 characters'})
		self.fields['phone_number'].error_messages.update({'required':'Phone number must be entered in the format +999999999 Up to 15 digits allowed.'})
		self.fields['address'].error_messages.update({'required':'Address can have maximum 40 characters'})
		self.fields['gender'].error_messages.update({'required':'Please select a gender'})
		self.fields['age'].error_messages.update({'required':'Age must be an integer'})
		self.fields['status'].error_messages.update({'required':'Please select an status'})
		self.fields['profile_pic'].error_messages.update({'required':'Please upload a profile picture'})

class UpdateForm(forms.ModelForm):
	class Meta:
		model=User
		fields=('email',)

	def __init__(self,*args,**kwargs):
		super(UpdateForm,self).__init__(*args,**kwargs)

		self.fields['email'].error_messages.update({'required':'Please enter valid  email'})

class FeedbackForm(forms.ModelForm):

	class Meta:
		model=Feedback
		fields=('title','text')
		label={
			'title':'Title',
			'text':'Description',
		}
	def __init__(self,*args,**kwargs):
		super(FeedbackForm,self).__init__(*args,**kwargs)
		self.fields['title'].error_messages.update({'required':'Title can hold atmost 50 characters'})
		self.fields['text'].error_messages.update({'required':'Description should only be 200 characters long'})

patient/templates/patient/appointment_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
<div class="content">
    <div class="row">
            <h4 class="page-title" style="text-align: center;">E HEALTH CARE</h4>
    </div>

        <div class="row">
            <div class="col-md-6">
                <div class="project-info-box mt-0">
                    <h5>APPOINTMENT DETAILS</h5>
                    <hr/>

                    <p><b>Appointment ID:</b><b>{{a.appointment_id.id}}</b></p>
                    <p><b>PATIENT NAME:</b>{{a.booked_by.name}}</p>
                    <p><b>CONTACT NUMBER:</b>{{a.booked_by.phone_number}}</p>
                    <p><b>EMAIL:</b>{{a.booked_by.user.email}}</p>
                    <p class="mb-0"><b>ADDRESS:</b>{{a.booked_by.address}}</p>
                </div>
                <hr/>
                <div class="project-info-box">
                    <p><b>DOCTOR NAME:</b>{{a.appointment_id.create_by.user.first_name}} {{a.appointment_id.create_by.user.last_name}}</p>
                    <p><b>APPOINTMENT DATE:</b>{{a.appointment_id.appointment_date|date:"M d, Y"}}</p>
                    <p><b>APPOINTMENT DAY:</b>{{a.appointment_id.appointment_day}}</p>
                    <p><b>AVAILABLE TIME:</b>{{a.appointment_id.appointment_start_time}}-{{a.appointment_id.appointment_end_time}}</p>
                </div><!-- / project-info-box -->

            </br>

        <a href="{{a.id}}/export_pdf" class="btn btn-info btn-user ">Download</a>

        <a href="{% url 'patient_appointment' %}" class="btn btn-secondary">View List</a>
    </div>
    </div>
</div>
</div>





{% endblock %}

patient/templates/patient/appointment_list.html
{% extends "base.html" %}
{% load static %}

{% block body_content %}

<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-3">
                <h4 class="page-title"> Appointments</h4>
            </div>

            <div class="col-sm-8 col-9 text-right m-b-20">
            <form class="form-inline my-2 my-lg-0 float-right" method="GET" action="" style="text-align: right;">
                <!-- {% csrf_token %} -->
                <input  type="text" class="form-control mr-sm-2" value="{{ request.GET.term }}" name="term" placeholder="Doctor name">
                <!-- <input value={{request.POST.term}} name="term" class="form-control mr-sm-2" type="text" placeholder="Search by speciality" aria-label="Search"> -->
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" value="submit">Search</button>
            </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive" style="max-height: 1000px; overflow-x: auto; overflow-y: auto;">
                    <table class="table table-border table-striped custom-table datatable mb-0">
                        <thead>
                            <tr>
                                <th>Appointment ID</th>
                                <th>Doctor Name</th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                                <th>Appointment Day</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for appointment in appointments %}
                            <tr>
                                <td>
                                    {{appointment.id}}
                                </td>
                                <td>{{appointment.create_by.user.first_name}} {{appointment.create_by.user.last_name}}</td>
                                <td>{{appointment.appointment_date|date:"M d, Y"}}</td>
                                <td>{{appointment.appointment_start_time}}-{{appointment.appointment_end_time}}</td>
                                <td>{{appointment.appointment_day}}</td>
                                <td class="text-right">
                                    {% if appointment.appointment_status == 0 %}
                                    <a class="btn btn-primary" href="take/{{appointment.id}}">Take Appoinment</a>
                                    {% else %}
                                    <button class="btn btn-danger">Already Booked</button>
                                    {% endif %}
                                    <!-- <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="edit/{{appointment.id}}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                            <a class="dropdown-item" data-toggle="tooltip" data-placement="top" title="Delete" href="delete/{{appointment.id}}" onclick="return confirm('Are you sure want to delete this appointment')">
                                                <i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                        </div>
                                    </div> -->
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

patient/templates/patient/dashboard.html
{% extends "base.html" %}

{% block body_content %}

<div class="page-wrapper" >
  <div class="content">
              <div class="row">
                  <div class="col-sm-12">
                      <h4 class="page-title"><strong>Please, choose at least 6 symptoms for prediction your disease.</strong></h4>
                  </div>
              </div>
          <div class="card-box" style="background-color: skyblue;">


    <form method="POST" action="/patient/dashboard/" enctype="multipart/form-data">
      {% csrf_token %}

         <h3 class="card-title"></h3>


        <h4>symptoms:</h4>
        <select class="selectpicker" name = 'value1' >
          <option>receiving_blood_transfusion</option>
          <option>red_sore_around_nose</option>
          <option>abnormal_menstruation</option>
          <option>continuous_sneezing</option>
          <option>breathlessness</option>
          <option>blackheads</option>
          <option>shivering</option>
          <option>dizziness</option>

        </select>

        <br>
        <br>
        <h4>symptoms:</h4>
        <select class="selectpicker" name = 'value2'>
          <option>back_pain</option>
          <option>unsteadiness</option>
          <option>yellow_crust_ooze</option>
          <option>muscle_weakness</option>
          <option>loss_of_balance</option>
          <option>chills</option>
          <option>ulcers_on_tongue</option>
          <option>stomach_bleeding</option>

        </select>
        <br>
        <br>
        <h4>symptoms:</h4>
        <select class="selectpicker" name = 'value3'>
          <option>lack_of_concentration</option>
          <option>coma</option>
          <option>neck_pain</option>
          <option>weakness_of_one_body_side</option>
          <option>diarrhoea</option>
          <option>receiving_unsterile_injections</option>
          <option>headache</option>
          <option>family_history</option>
        </select>
        <br>
        <br>
        <h4>symptoms:</h4>
        <select class="selectpicker" name = 'value4' >
          <option>fast_heart_rate</option>
          <option>pain_behind_the_eyes</option>
          <option>sweating</option>
          <option>mucoid_sputum</option>
          <option>spotting_urination</option>
          <option>sunken_eyes</option>
          <option>dischromic_patches</option>
          <option>nausea</option>

        </select>
        <br>
        <br>
        <h4>symptoms:</h4>
        <select class="selectpicker" name ='value5'>
          <option>dehydration</option>
          <option>loss_of_appetite</option>
          <option>abdominal_pain</option>
          <option>stomach_pain</option>
          <option>yellowish_skin</option>
          <option>altered_sensorium</option>
          <option>chest_pain</option>
          <option>muscle_wasting</option>
        </select>
        <br>
        <br>
        <h4>symptoms:</h4>
        <select class="selectpicker" name = 'value6'>
          <option>vomiting</option>
          <option>mild_fever</option>
          <option>high_fever</option>
          <option>red_spots_over_body</option>
          <option>dark_urine</option>
          <option>itching</option>
          <option>yellowing_of_eyes</option>
          <option>fatigue</option>
          <option>joint_pain</option>
          <option>muscle_pain</option>
        </select>
        <br>
        <br>
        <br>
          <button type="Check" class="btn btn-primary btn-user "> Submit</button>
    </form>
    </div>
    </div>
    </div>



  {% endblock %}

patient/templates/patient/feedback_form.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
<div class="content"> 
    <div class="row">
            <h4 class="page-title">Update Feedback</h4>
    </div>
    <!-- <div class="row"> -->
            <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                 <input class="form-control" type="text" name="title" value="{{feedback.title}}" maxlength="50" required id="id_title">
                </div>
            <div class="form-group">
                <label for="id_text">Description</label> 
                <textarea class="form-control" name="text" cols="40" rows="10" maxlength="200" required id="id_text">
                    {{feedback.text}}
                </textarea>
                </div>
           
        <div class="form-group">
             <label for="id_picture">Picture Currently:</label> <a href="feedback.picture.url">{{feedback.picture}}</a><br>
                <input value="feedback.picture.url" class="form-control" type="file" name="picture" accept="image/*" id="id_picture">
        </div> 
        <button type="submit" class="btn btn-info btn-user ">Update Feedback</button>         
        
        <a href="{% url 'feedback' %}" class="btn btn-secondary">Cancel</a>
    </form>
    <!-- </div> -->
</div>
</div>

{% endblock %}

patient/templates/patient/image.html
{% extends "base.html" %}
{% block body_content %}


<div class="page-wrapper" >
    <div class="content" style="background-color: skyblue;">
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title"> <strong>Please upload Your X-ray Image</strong></h4>
            </div><br><br><br><br>
            <h4 class="mb-5"> <strong>{{sur}}</strong> </h4>
        </div>
    </div>
<div>
<div class="card-box"style="background-color: skyblue;" >
      <div class="container">
        <div class="row">
          <div class=" col md-12">
            <h4>Image Uploader</h4><br><br>
            <div>
            <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Upload"/>
            </form>
        </div>
      </div>




    </div>
</div>


<div class="card-box" style="background-color: skyblue;">
    {% if disease_doctor_list.all %}
      <h5>Suggested Doctor Information</h5>
      <div class="container">
        <div class="row">
          <div class=" col md-12">

              <table class="table table-border table-striped custom-table datatable mb-0" style="max-height: 500px; overflow-x: auto; overflow-y: auto;">
                <thead>
                  <tr>
                    <th scope="col">DoctorID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Department</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone Number</th>
                  </tr>
                </thead>
                <tbody>
                  {% for doctor in disease_doctor_list %}
                  <tr>
                    <th> {{doctor.doctorID}}</th>
                    <th> {{doctor.user.first_name}}&nbsp;{{doctor.user.last_name}}</th>
                    <th>{{doctor.department}}</th>
                    <td>{{doctor.user.email}}</td>
                    <td>{{doctor.phone_number}}</td>
                  </tr>
                  {% endfor %}

                </tbody>
                  </table>
                  {% else %}
                  <h5>No Doctor Available </h5>
            {% endif %}
</div>
{% endblock %}

patient/templates/patient/profile.html
{% extends "base.html" %}

{% block body_content %}
        <div class="page-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">Edit Profile</h4>
                    </div>
                </div>

<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
   <div class="card-box">
                       <h3 class="card-title">My Informations</h3>
  <div class="form-group">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}"  name="email"
      maxlength="254" id="id_email">
      <span class="text-danger" >
        {{user_form.email.errors}}
</span>
  </div>
  <br />
  <div class="form-group"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20"  class="form-control">
      <span class="text-danger" >
        {{patient_profile.name.errors}}
</span>
    </div>

  <br />
  <div class="form-group"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17">
      <span class="text-danger" >
        {{patient_profile.phone_number.errors}}
</span>
  </div>
  <br />
  <div class="form-group"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40">
      <span class="text-danger" >
        {{patient_profile.address.errors}}
</span>
  </div>
  <br />
  <div class="form-group"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select>
      <span class="text-danger" >
        {{patient_profile.gender.errors}}
</span>
    </div>
  <br />
  <div class="form-group"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20">
      <span class="text-danger" >
        {{patient_profile.age.errors}}
</span>
    </div>
  <br />
  <div class="form-group"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select>

        <span class="text-danger" >
          {{patient_profile.status.errors}}
  </span>
      </div><br />

  <div class="form-group"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*"  value="{{request.user.profile.profile_pic}}">
    <span class="text-danger" >
      {{patient_profile.profile_pic.errors}}
</span>
  </div>
  <br />


  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />

  </div>


</form>
</div>
</div>


<!--
<h4 class="mb-5">My Profile</h4>
<div align="center">
   {% if request.user.profile.profile_pic.url != '' %}
  <img src="{{request.user.profile.profile_pic.url}}" alt="Images" height="300px"/>
  {% else %}
  <i class="fas fa-10x fa-user-circle"></i>
  {% endif %}
</div>
<div class="card-body">
</div>

-->
<!--


<div  class="card text-white bg-secondary mb-3" >
  <div class="card-body">
  <div class="card-group">
    <br />

<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-inline">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}" style="width: 300px;" type="email" name="email"
      maxlength="254" id="id_email">
  </div>
  <br />
  <div class="form-inline"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20" required id="id_name" class="form-control"></div>

  <br />
  <div class="form-inline"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17"
      id="id_phone_number"></div>
  <br />
  <div class="form-inline"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40" required
      id="id_address"></div>
  <br />
  <div class="form-inline"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select></div>
  <br />
  <div class="form-inline"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20" required id="id_age"></div>
  <br />
  <div class="form-inline"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select></div><br />

  <div class="form-inline"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*" id="id_profile_pic"></div>
  <br />
  <br />

  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />
  <br />
</form>
</div>
  </div>
</div>

-->


{% endblock %}