Disease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('appointment/', include('appointment.urls')),
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('doctor/',include('doctor.urls')),
    path('roleadmin/',include('roleadmin.urls')),
    path('patient/',include('patient.urls')),
    path('health/',include('Health.urls')),
    path('', RedirectView.as_view(url="health/")),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = 'Smart Health'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"

roleadmin/urls.py
from django.urls import path
from roleadmin import views

urlpatterns=[
    path('admin_dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('roleadmin_login/',views.roleadmin_login,name="roleadmin_login"),
    path('roleadmin_logout/',views.roleadmin_logout,name="roleadmin_logout"),
    path('doctors_list/',views.doctors_list,name="doctors_list"),
    path('doctors_list/add',views.add_doctor),
    path('doctors_list/edit/<int:pk>',views.edit_doctor),
    path('doctors_list/delete/<int:pk>',views.delete_doctor),
    path('patients_list/',views.patients_list,name="patients_list"),
    path('patients_list/view_profile/<int:pk>',views.patient_profile),
    path('patients_list/delete/<int:pk>',views.patient_delete),
    path('disease/',views.disease,name="disease"),
    path('disease/add',views.assign_disease),
    path('disease/edit/<int:pk>',views.edit_disease),
    path('disease/delete/<int:pk>',views.delete_disease),
    path('our_feedback/',views.our_feedback,name="our_feedback"),
    path('our_feedback/detail/<int:pk>',views.our_feedback_detail),
]

urls.py
from django.contrib import admin
from django.urls import path,include
from doctor import views
from django.views.generic.base import RedirectView

urlpatterns = [        
path('doctor/',RedirectView.as_view(url='doctor_login/')),
path('doctor_login/', views.doctor_login,name='doctor_login'),
path('prescription/', views.prescription,name='prescription'),

path('dashboard_doctor/', views.dashboard_doctor, name="dashboard_doctor"),
path('doctor_logout/', views.doctor_logout, name="doctor_logout"),
path('appointment/', views.appointment, name="appointment"),
path('book_appointment/',views.book_appointment,name="book_appointment"),
path('appointment/add_appointment/',views.add_appointment),
path('appointment/edit/<int:pk>',views.edit_appointment),
path('appointment/delete/<int:pk>',views.delete_appointment),
path('book_appointment/delete/<int:pk>',views.delete_booked_appointment),


]

doctor/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


# Create your models here.
class DoctorInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    address=models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    picture=models.ImageField(blank=True,null=True)
    department=models.CharField(max_length=30)
    gender=models.CharField( max_length=50,blank=True,choices=(('Female','Female'),('Male','Male'),('Other','Other')))
    doctorID=models.CharField(max_length=50,unique=True)
    education_college=models.CharField(max_length=100)
    education_degree=models.CharField(max_length=100)
    education_year=models.DateTimeField()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_instance(self):
        return self

roleadmin/models.py
from django.db import models

# Create your models here.

roleadmin/forms.py
from patient.models import Disease1
from doctor.models import DoctorInfo
from django import forms

class AddDiseaseForm(forms.ModelForm):
    name=forms.CharField(widget=forms.TextInput(),label='Disease Name',error_messages={'required':'Enter upto 200 characters'})
    doctor=forms.ModelChoiceField(queryset=DoctorInfo.objects.all(),initial=0,error_messages={'required':'Please select a doctor'})

    class Meta:
        model=Disease1
        fields=["name","doctor",]

    def __init__(self,*args,**kwargs):
        super(AddDiseaseForm,self).__init__(*args,**kwargs)
        self.fields['name'].error_messages.update({'required':'Enter upto 200 characters'})
        self.fields['doctor'].error_messages.update({'required':'Please select a doctor'})

roleadmin/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from doctor.models import DoctorInfo
from patient.models import Profile,Feedback,Disease1,WhoPredictDisease
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.db.models import Q
from doctor.forms import DoctorForm,DoctorUserForm
from roleadmin.forms import AddDiseaseForm
from django.db.models.functions import Concat
from django.db.models import Value
from roleadmin.decoratos import allowed_users,unauthenticated_admin

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def admin_dashboard(request):
    doctors=DoctorInfo.objects.all().count()
    users=User.objects.filter(groups__name="PATIENT").count()
    feedbacks=Feedback.objects.all().count()
    doctorinfo=DoctorInfo.objects.all().order_by('-id')
    predictions=WhoPredictDisease.objects.all().count()
    patient_list=WhoPredictDisease.objects.all().order_by('-id')
    context={
        'doctors':doctors,
        'patients':users,
        'feedbacks':feedbacks,
        'doctorinfo':doctorinfo,
        'predictions':predictions,
        'patient_list':patient_list,
    }
    return render(request,'roleadmin/dashboard.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def disease(request):
    search_term=request.GET.get('term')
    if search_term is not None:
        search_term = search_term.lstrip().rstrip()
    if search_term==None:
        search_term=""
    diseases = Disease1.objects.annotate(fullname=Concat('doctor__user__first_name', Value(' '), 'doctor__user__last_name')).filter(Q(name__icontains=search_term) | Q(doctor__user__first_name__icontains=search_term) | Q(doctor__user__last_name__icontains=search_term) | Q(fullname__icontains=search_term)).order_by('-id')
    # diseases=Disease1.objects.filter(Q(name__icontains=search_term)|Q(doctor__user__first_name__icontains=search_term)|Q(doctor__user__last_name__icontains=search_term)).order_by('-id')

    context={
        'diseases':diseases,
    }
    return render(request,'roleadmin/disease.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def assign_disease(request):
    if request.method=="POST":
        assign_disease_form=AddDiseaseForm(request.POST or None)
        if assign_disease_form.is_valid():
            assign_disease_form.save()
            return redirect('disease')
        else:
            context={
                'assign_disease_form':assign_disease_form
            }
            return render(request,'roleadmin/assign_disease_form.html',context)
    else:
        assign_disease_form=AddDiseaseForm()
        context={
            'assign_disease_form':assign_disease_form
        }
        return render(request,'roleadmin/assign_disease_form.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def edit_disease(request,pk):
    try:
        disease=Disease1.objects.get(id=pk)
    except:
        return redirect('disease')
    assign_disease_form=AddDiseaseForm(request.POST,instance=disease)
    mydict={'assign_disease_form':assign_disease_form,'disease':disease}
    if request.method=='POST':
        assign_disease_form=AddDiseaseForm(request.POST,instance=disease)
        if assign_disease_form.is_valid():
            assign_disease_form.save()
            return redirect('disease')
    return render(request,'roleadmin/assign_disease_edit_form.html',context=mydict)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def delete_disease(request,pk):
    try:
        disease=Disease1.objects.get(id=pk)
    except:
        return redirect('disease')
    disease.delete()
    return redirect('disease')


@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def doctors_list(request):
    page=request.GET.get('page',1)
    search_term=request.GET.get('term')
    if search_term is not None:
        search_term = search_term.lstrip().rstrip()

    if search_term==None:
        search_term=""
    doctors = DoctorInfo.objects.annotate(fullname=Concat('user__first_name', Value(' '), 'user__last_name')).filter(Q(user__first_name__icontains=search_term) | Q(user__last_name__icontains=search_term) | Q(address__icontains=search_term) | Q(department__icontains=search_term) | Q(fullname__icontains=search_term))
    # doctors=DoctorInfo.objects.filter(Q(user__first_name__icontains=search_term) |Q(user__last_name__icontains=search_term)|Q(address__icontains=search_term)| Q(department__icontains=search_term))
    paginator=Paginator(doctors,8)
    try:
        doctors=paginator.page(page)
    except PageNotAnInteger:
        doctors=paginator.page(1)
    except EmptyPage:
        doctors=paginator.page(paginator.num_pages)
    context={
        'doctors':doctors,
    }
    return render(request,'roleadmin/doctor_list.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def add_doctor(request):
    userForm=DoctorUserForm()
    doctor_add_form=DoctorForm()
    mydict={'userForm':userForm,'doctor_add_form':doctor_add_form}
    if request.method=='POST':
        userForm=DoctorUserForm(request.POST)
        doctor_add_form=DoctorForm(request.POST,request.FILES)
        if userForm.is_valid() and doctor_add_form.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            doctor=doctor_add_form.save(commit=False)
            doctor.user=user
            doctor.save()
            my_doctor_group=Group.objects.get_or_create(name='DOCTOR')
            my_doctor_group[0].user_set.add(user)
            return redirect('doctors_list')
        else:
            mydict={'userForm':userForm,'doctor_add_form':doctor_add_form}
            return render(request,'roleadmin/doctor_add_form.html',context=mydict)
    return render(request,'roleadmin/doctor_add_form.html',context=mydict)



@login_required(login_url='roleadminlogin')
@allowed_users(allowed_roles=['ADMIN'])
def edit_doctor(request,pk):
    try:
        doctor=DoctorInfo.objects.get(id=pk)
    except:
        return redirect('doctors_list')
    user=User.objects.get(id=doctor.user_id)
    userForm=DoctorUserForm(instance=user)
    doctor_add_form=DoctorForm(request.FILES,instance=doctor)
    mydict={'userForm':userForm,'doctor_add_form':doctor_add_form,'doctor':doctor}
    if request.method=='POST':
        userForm=DoctorUserForm(request.POST,instance=user)
        doctor_add_form=DoctorForm(request.POST,request.FILES,instance=doctor)
        if userForm.is_valid() and doctor_add_form.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            doctor_add_form.save()
            return redirect('doctors_list')
        else:
            mydict={'userForm':userForm,'doctor_add_form':doctor_add_form}
            return render(request,'roleadmin/doctor_add_form.html',context=mydict)
    return render(request,'roleadmin/doctor_edit_form.html',context=mydict)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def delete_doctor(request,pk):
    try:
        doctor=DoctorInfo.objects.get(id=pk)
    except:
        return redirect('doctors_list')
    user=User.objects.get(id=doctor.user_id)
    user.delete()
    doctor.delete()
    return redirect('doctors_list')

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def patients_list(request):
    search_term=request.GET.get('term')
    if search_term is not None:
        search_term = search_term.lstrip().rstrip()

    users=User.objects.filter(groups__name="PATIENT")
    if search_term==None:
        search_term=""
    patients=Profile.objects.filter(user_id__in=users).filter(Q(name__icontains=search_term) | Q(user__email__icontains=search_term) | Q(address__icontains=search_term))
    context={
        'patients':patients,
    }
    return render(request,'roleadmin/patient_list.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def patient_profile(request,pk):
    try:
        users=User.objects.filter(groups__name="PATIENT")
        patient=Profile.objects.filter(user_id__in=users).get(id=pk)

    except:
        return redirect('patients_list')
    context={
        'patient':patient
    }
    return render(request,'roleadmin/patient_profile.html',context)

@login_required(login_url="roleadmin_login")
@allowed_users(allowed_roles=['ADMIN'])
def patient_delete(request,pk):
    try:
        users=User.objects.filter(groups__name="PATIENT")
        patient=Profile.objects.filter(user_id__in=users).get(id=pk)
    except:
        return redirect('patients_list')

    patient.delete()
    return redirect('patients_list')

@login_required(login_url='roleadmin_login')
@allowed_users(allowed_roles=['ADMIN'])
def our_feedback(request):
    page=request.GET.get('page',1)
    feedbacks=Feedback.objects.all().order_by('-id')
    paginator=Paginator(feedbacks,9)
    try:
        feedbacks=paginator.page(page)
    except PageNotAnInteger:
        feedbacks=paginator.page(1)
    except EmptyPage:
        feedbacks=paginator.page(paginator.num_pages)
    context={
        'feedbacks':feedbacks
    }
    return render(request,'roleadmin/feedback.html',context)

@login_required(login_url='roleadmin_login')

roleadmin/templates/roleadmin/assign_disease_edit_form.html
{% extends 'base_admin.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Disease and Doctor</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <form method="POST" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="id_name">Disease</label>
                                <input value="{{disease.name}}" class="form-control" type="text" name="name" maxlength="200" required id="id_name">
                                <br />
                                <span class="text-danger" >
                                    {{assign_disease_form.name.errors}}
                            </span>
                        </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                              {{ assign_disease_form.doctor|as_crispy_field}}
                              <span class="text-danger" >
                                {{assign_disease_form.doctor.errors}}
                        </span>
                            </div>
                        </div>
                  </div>
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Asign Doctor</button>
                  <br/>
                          <a href="{% url 'disease' %}" class="btn btn-secondary btn-lg btn-block">Cancel</a>
                    <!-- <label for="id_name">Name</label>
                    <input type="text" name="name" required id="id_name" class="form-control"> -->
                  </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

roleadmin/templates/roleadmin/assign_disease_form.html
{% extends 'base_admin.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Disease and Doctor</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <form method="POST" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                             {{ assign_disease_form.name|as_crispy_field }}
                             <span class="text-danger" >
                                {{assign_disease_form.name.errors}}
                        </span>
                        </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                              {{ assign_disease_form.doctor|as_crispy_field}}
                              <span class="text-danger" >
                                {{doctor_add_form.doctor.errors}}
                        </span>
                            </div>

                        </div>
                  </div>
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Add Doctor</button>
                  <br/>
                          <a href="{% url 'disease' %}" class="btn btn-secondary btn-lg btn-block">Cancel</a>
                    <!-- <label for="id_name">Name</label>
                    <input type="text" name="name" required id="id_name" class="form-control"> -->
                  </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

roleadmin/templates/roleadmin/doctor_edit_form.html
{% extends 'base_admin.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Doctor</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ userForm.first_name|as_crispy_field }}
                                <!-- <label for="id_name">Doctor Name</label>  -->
                                <span class="text-danger" >
                                    {{userForm.first_name.errors}}
                            </span>
                                <!-- <input value="" class="form-control" type="text" name="name" maxlength="40" required id="id_name"> -->
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ userForm.last_name|as_crispy_field }}
                                <!-- <label for="id_name">Doctor Name</label>  -->
                                <span class="text-danger" >
                                    {{userForm.last_name.errors}}
                            </span>
                                <!-- <input value="" class="form-control" type="text" name="name" maxlength="40" required id="id_name"> -->
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                            {{ userForm.email|as_crispy_field }}
                                <!-- <label for="id_email">Email:</label>     -->

                                <span class="text-danger" >
                                    {{userForm.email.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ userForm.username|as_crispy_field }}
                                <span class="text-danger" >
                                    {{userForm.username.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ userForm.password|as_crispy_field }}
                                <span class="text-danger" >
                                    {{userForm.password.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="id_address">Address</label>
                                <input value="{{doctor.address}}" class="form-control" type="text" name="address" maxlength="100">
                                <span class="text-danger" >
                                    {{doctor_add_form.address.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ doctor_add_form.phone_number|as_crispy_field }}
                                <!-- <label for="id_phone_number">Phone Number</label>  -->
                                <!-- <input value="{{doctor.phone_number}}" class="form-control" type="text" name="phone_number" maxlength="17">  -->
                                <span class="text-danger" >
                                    {{doctor_add_form.phone_number.errors}}
                            </span>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                {{doctor_add_form.picture|as_crispy_field}}
                                <span class="text-danger" >
                                    {{doctor_add_form.picture.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                        <div class="form-group">
                            {{doctor_add_form.gender|as_crispy_field}}
                            <span class="text-danger" >
                                {{doctor_add_form.gender.errors}}
                        </span>

                        </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="id_doctorID">Doctor ID</label>

                                <input value="{{doctor.doctorID}}" class="form-control" type="text" name="doctorID" maxlength="50">
                                <span class="text-danger" >
                                    {{doctor_add_form.doctorID.errors}}
                            </span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                            <label for="id_department">Department</label>
                            <input value="{{doctor.department}}" class="form-control" type="text" name="department" maxlength="30">
                            <span class="text-danger" >
                                {{doctor_add_form.department.errors}}
                        </span>
                        </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                        <label for="id_education_college">Education college</label>
                        <input value="{{doctor.education_college}}" class="form-control" type="text" name="education_college" maxlength="100">
                        <span class="text-danger" >
                            {{doctor_add_form.education_college.errors}}
                    </span>

                    </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="id_education_degree">Education degree</label>
                                    <input value="{{doctor.education_degree}}" class="form-control" type="text" name="education_degree" maxlength="100">
                                    <span class="text-danger" >
                                        {{doctor_add_form.education_degree.errors}}
                                </span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{doctor_add_form.education_year|as_crispy_field}}
                                    <span class="text-danger" >
                                        {{doctor_add_form.education_year.errors}}
                                </span>
                            </div>
                            </div>
                            <!-- <input class="form-control" id="date" name="date" placeholder="MM/DD/YYY" type="text"/> -->

                        </div>

                        <button type="submit" class="btn btn-primary btn-lg btn-block">Update Doctor</button>
                        <br/>
                        <a href="{% url 'doctors_list' %}" class="btn btn-secondary btn-lg btn-block">Cancel</a>

                </form>

            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

roleadmin/templates/roleadmin/feedback.html
{% extends 'base_admin.html' %}
{% load static %}

{% block body_content %}

<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-8 col-4">
                <h4 class="page-title">Feedback</h4>
            </div>
            <!-- <div class="col-sm-4 col-8 text-right m-b-30">
                <a class="btn btn-primary btn-rounded float-right" href="add_feedback"><i class="fa fa-plus"></i> Add Feedback</a>
            </div> -->
        </div>
        <div class="row">
            {% for feedback in feedbacks %}
            <div class="col-sm-6 col-md-6 col-lg-4">
                <div class="blog grid-blog">
                    <!-- <div class="blog-image">
                        <a href=""><img style="width:fit-content; height:200px;" class="img-fluid" src="{{feedback.picture.url}}" alt="No picture found"></a>
                    </div> -->
                    <div class="blog-content">
                        <h3 class="blog-title"><a href="detail/{{feedback.id}}">{{feedback.title}}</a></h3>
                        <!-- <p>Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor incididunt ut labore etmis dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris.</p> -->
                        <a href="detail/{{feedback.id}}" class="read-more"><i class="fa fa-long-arrow-right"></i> Read More</a>
                        <!-- <a type="button" class="btn btn-light float-right" href="edit/{{feedback.id}}">Edit</a> -->
                        <div class="blog-info clearfix">
                            <div class="post-left">
                                <ul>
                                    <li style="font-weight: bold;"><i class="fa fa-calendar"></i> <span>Uploaded Date:{{feedback.date | date:"d/m/y"}}</span></li>
                                </ul>
                            </div>
                            <div class="post-right">
                                <!-- <a class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete" href="delete/{{feedback.id}}" onclick="return confirm('Are you sure want to delete Feedback : {{feedback.title}}')"> -->
                                    <!-- <i class="fas fa-trash"></i> -->
                                <!-- Delete -->
                                <!-- </a> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% if feedbacks.has_other_pages %}
         <nav aria-label="Page navigation example">
         <ul class="pagination justify-content-center"">

         {% if feedbacks.has_previous %}
         <li class="page-item">
         <a class="page-link" href="#" aria-label="Previous">
         <span aria-hidden="true">&laquo;</span>
         </a>
         </li>

         {% else %}
         <li class="page-item disabled">
         <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
         </li>

         {% endif %}

         {% for i in feedbacks.paginator.page_range %}
         {% if feedbacks.number == i %}
              <li class="page-item active" aria-current="page">
                 <a class="page-link" href="#">{{i}} <span class="sr-only">(current)</span></a>
             </li>
         {% else %}
           <li class="page-item"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
         {% endif %}
         {% endfor %}

         {% if feedbacks.has_next %}
         <li class="page-item">
         <a class="page-link" href="#" aria-label="Next">
         <span aria-hidden="true">&raquo;</span>
         </a>
         </li>
         {% else %}
         <li class="page-item disabled">
         <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
         </li>
         {% endif %}
         </ul>
         </nav>
         {% endif %}
</div>

{% endblock %}